pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
    plugins {
        id 'com.android.application' version '8.3.0'
        id 'org.jetbrains.kotlin.android' version '1.8.22'
        id 'org.jetbrains.kotlin.plugin.parcelize' version '1.8.22'
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "ServiLine"
include ':app'
