# # spring.application.name=labangonline-backend
# 
# spring.datasource.url=jdbc:postgresql://db.ashaantifmdzgtyeoibh.supabase.co:5432/postgres?sslmode=require
# spring.datasource.username=postgres
# spring.datasource.password=Lenonlee@7312005
# spring.datasource.driver-class-name=org.postgresql.Driver
# 
# spring.datasource.hikari.maximum-pool-size=5
# spring.datasource.hikari.connection-timeout=30000
# 
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=false
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.properties.hibernate.format_sql=true
# 
# server.port=8080
# frontend.url=${FRONTEND_URL:http://localhost:5173}
# 
# NEXT_PUBLIC_SUPABASE_URL=https://ashaantifmdzgtyeoibh.supabase.co
# NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=sb_publishable_VCUNKblYs0mxsZoGhr3z8w_pUL-fckh

spring.application.name=labangonline-backend

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.ashaantifmdzgtyeoibh
spring.datasource.password=Lenonlee@7312005
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

server.address=0.0.0.0
server.port=8080
frontend.url=${FRONTEND_URL:http://localhost:5173}